name: Dedupe Dependabot PRs

on:
  push:
    branches: ['dependabot/npm_and_yarn/**']

permissions:
  contents: write

jobs:
  dedupe:
    runs-on: ubuntu-latest

    steps:
      - uses: laboperator-gmbh/github-actions/yarn/dedupe@v1
